image: node:12-buster

stages:
  - build
  - publish

build:
  stage: build
  script:
    - yarn install --frozen-lockfile --non-interactive
    - yarn run typecheck
    - yarn run lint
    - yarn run test --ci --coverage --reporters=default --reporters=jest-junit
    - yarn run build
  coverage: '/Statements\s*:\s*(\d+\.\d+)%/'
  artifacts:
    paths:
      - dist/
    reports:
      junit: junit.xml

publish:
  stage: publish
  only:
    refs:
      - master
  script:
    - npx @manuscripts/publish
